### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by gylaz** [thoughtbot/hound-cli#1]

**Comment by wulymammoth** [comment]
@gylaz is this usable yet? If so, could you please update the README? The RealReal has Hound CI in its repos, but we'd love to be able to run Hound locally before pushing to CI if possible.

**Comment by gylaz** [comment]
@sudostack This isn't usable, AFAIK. I don't actually remember what state we left this in. It was a thing we worked on during a hackathon, but didn't quite get it to a usable state. We may come back to it, but for the time I would consider this abandonware.

To be honest, I'm trying to remember what the original intent for this tool was. I think it was to quickly check a repo's configuration to see if it's valid or not. That was to be a V1 anyway.

You're welcome to submit a PR, if you think this would be useful.

**Comment by croaky** [comment]
Maybe we shut this repo down to avoid confusion, @gylaz?
